//! Command-line interface for the LP-0002 Private M-of-N Multisig program.
//!
//! Delegates entirely to `spel::run()`, the generic IDL-driven CLI in
//! `spel-framework v0.3.0`. The IDL JSON at the path declared in
//! `spel.toml` (generated by `cargo run -p private_multisig_idl_gen >
//! private_multisig.idl.json`) drives every subcommand: each
//! `#[instruction]` handler in the verifier becomes a kebab-case
//! subcommand; PDAs are auto-computed from the `pda = [...]` annotations;
//! risc0 wire serialization happens for free.
//!
//! ## The `approve` handler — known limitation
//!
//! `approve` is the one structurally-special instruction: the verifier
//! body calls `env::verify(APPROVE_CIRCUIT_IMAGE_ID, public_inputs)`,
//! which adds a Risc0 composition assumption that the outer sequencer
//! prover must discharge by being handed the inner approval receipt as
//! an `ExecutorEnv::add_assumption(receipt)`. The current
//! `sequencer_service_rpc` surface (v0.2.0-rc3) does not accept
//! attached receipts on the public transaction wire — only the 96-byte
//! `public_inputs` and 32-byte `nullifier` ride the instruction data.
//!
//! Consequence: running `pmsig approve` against a live remote sequencer
//! will fail to finalize because the outer prover can't discharge the
//! assumption. The happy path is exercised by the step-7 end-to-end
//! integration test, which runs the prover in-process with both
//! receipts on hand. Real production submission of `approve` against a
//! remote sequencer needs either (a) a sequencer RPC extension that
//! accepts attached receipts, or (b) a local-prove path that produces a
//! full outer receipt before submitting — both deferred to follow-on
//! work per PLAN.md §"Out of scope for this plan (explicit)".
//!
//! The other 5 handlers (`create-multisig`, `create-vault`, `propose`,
//! `execute`, `reject`) work end-to-end through this CLI.

#[tokio::main]
async fn main() {
    spel::run().await;
}
